/** Port of `CatalogDestination`. */
export type CatalogDestination =
  | 'Home'
  | 'Buttons'
  | 'Toggle'
  | 'Slider'
  | 'BottomTabs'
  | 'Dialog'
  | 'LockScreen'
  | 'ControlCenter'
  | 'Magnifier'
  | 'GlassPlayground'
  | 'AdaptiveLuminanceGlass'
  | 'ProgressiveBlur'
  | 'ScrollContainer'
  | 'LazyScrollContainer'
